export const custIngredients = [
    "candy",
    "cilantro",
    "star anise",
    "blueberry",
    "violet",
    "orange",
    "grapefruit",
    "apple",
    "nutmeg",
    "pear",
    "pecan",
    "kiwi",
    "fallen leaves",
    "crisp air",
    "frost",
    "melancholy",
    "introspection",
    "hope",
    "renewal",
    "autumn",
    "nostalgia",
    "transformation",
    "vibrant colors",
    "loud flavors",
    "excessive sweetness",
    "overpowering spices"
];